"""Retrieval subagents (client section 9):
  1 Query Understanding  2 Corpus Selection  3 Retrieval
  4 Evaluation          5 Reranking         6 Response Generation
Each works offline (heuristics) and uses the LLM when a key is configured."""
from __future__ import annotations

import json
import re
from collections import defaultdict
from typing import Dict, List, Optional, Tuple

from ..engine import Engine
from ..models import QueryPlan, RetrievalHit, Answer, ChunkRecord
from ..util import content_tokens, cosine
from .bm25 import BM25

# ---------------------------------------------------------------------------
REL_WORDS = ("connect", "related", "relationship", "link", "between", "tie",
             "associat", "network", "pattern", "common", "shared", "across",
             "repeat", "trend", "trafficking ring", "ring")
TIMELINE_WORDS = ("timeline", "over time", "history", "chronolog", "trend",
                  "since", "between 20", "sequence")
TABLE_WORDS = ("table", "column", "row", "how many", "count", "total", "rate",
               "statistic", "number of", "how much", "statistics")
VISUAL_WORDS = ("chart", "graph", "figure", "image", "photo", "diagram", "map")
ENTITY_WORDS = ("who is", "what is", "tell me about", "profile of")
ALL_WORDS = ("all sources", "everything", "every", "across all", "all data",
             "entire dataset", "all corpus", "all corpuses", "all corpora")
MANUFACTURE_WORDS = ("manufactur", "production volume", "produced by", "made in",
                     "how many made", "total produced", "pistols made", "rifles made",
                     "manufacturing output", "firearms produced")
EXPORT_WORDS = ("export", "exported", "exports", "sold abroad", "shipped to",
                "foreign buyer", "breakdown of exported", "exported firearm")
IMPORT_WORDS = ("import", "imported", "imports", "foreign manufacturer",
                "brought into", "imported from", "country of origin",
                "imported firearms", "firearm imports")
GHOST_GUN_WORDS = ("ghost gun", "privately made", "pmf", "unserialized",
                   "3d printed", "unregistered", "home made firearm")
TRACE_WORDS = ("trace", "traced", "tracing", "ntc", "etrace", "crime gun",
               "source state", "time to crime", "firearm trace")
THEFT_WORDS = ("stolen", "theft", "lost", "missing", "ffl theft", "dealer theft",
               "burglary", "robbery of dealer")
ARSON_WORDS = ("arson", "fire incident", "incendiary", "house of worship fire",
               "structure fire", "vehicle fire")
EXPLOSIVE_WORDS = ("explosive", "bomb", "pipe bomb", "ied", "pyrotechnic",
                   "detonator", "blast", "explosion incident")
SELLING_WORDS = ("top selling", "best selling", "most sold", "caliber", "calibres",
                 "selling distribution", "retail sales", "firearms sold")

# Per-corpus BM25 cache: corpus_name -> (chunk_count, BM25_instance, source_chunk_counts)
_BM25_CACHE: Dict[str, Tuple[int, "BM25", Dict[str, int]]] = {}

# ---------------------------------------------------------------------------
# Chunk quality filter — penalise navigation/TOC/URL/summary garbage chunks
# so they don't crowd out actual data chunks after BM25 keyword boosting.
# ---------------------------------------------------------------------------
_URL_STRIP_RE = re.compile(r'https?://\S+')
_DOC_SUMMARY_RE = re.compile(r'^\[DOC SUMMARY')
_TIMESTAMP_RE = re.compile(r'\d{1,2}/\d{1,2}/\d{2,4},?\s*\d{1,2}:\d{2}\s*(?:AM|PM)?', re.I)
_TOC_NUMBERED_RE = re.compile(
    r'^\s*\d+[\.\)]\s+(?:Table|Chart|Figure|Appendix|Graph|Section)\b',
    re.MULTILINE | re.IGNORECASE,
)
# Detect section-outline lines: "  3.1  Some Title  ....  13"
_SECTION_OUTLINE_RE = re.compile(r'^\s*\d+(?:\.\d+)*\s+\w.*\s{4,}\d+\s*$', re.MULTILINE)


def _chunk_quality(chunk: "ChunkRecord") -> float:
    """Return a quality multiplier [0.1, 1.0] for *chunk*.

    Low scores are assigned to:
    • Doc-summary headers ([DOC SUMMARY: …])
    • URL-only or navigation fragments (mostly URL with little text)
    • Table-of-contents pages (numbered Table:/Figure: listings)
    • Section-outline pages (heading + big whitespace gap + page-number)
    • Micro-chunks (< 60 effective chars after stripping URLs/timestamps)
    """
    text = chunk.text
    n = len(text.strip())
    if n < 60:
        return 0.15

    # Doc summary headers (generated by the indexer — metadata, not content)
    if _DOC_SUMMARY_RE.match(text):
        return 0.20

    # Strip URLs and measure remaining content density
    text_no_url = _URL_STRIP_RE.sub('', text).strip()
    if len(text_no_url) < 50:
        return 0.10  # Almost entirely URL

    # Timestamp-only navigation chunks (web-scrape headers like "6/7/26, 10:05 PM ...")
    ts_count = len(_TIMESTAMP_RE.findall(text))
    if ts_count >= 1 and len(text_no_url.replace('\n', '').strip()) < 120:
        return 0.15

    lines = [l.strip() for l in text.splitlines() if l.strip()]

    # TOC: numbered "N. Table: …" or "N. Figure: …" listings
    toc_count = len(_TOC_NUMBERED_RE.findall(text))
    if toc_count >= 2 and toc_count / max(len(lines), 1) >= 0.25:
        return 0.20

    # Section outline: "3.1  Title          13" repeated lines
    outline_count = len(_SECTION_OUTLINE_RE.findall(text))
    if outline_count >= 3 and outline_count / max(len(lines), 1) >= 0.30:
        return 0.20

    return 1.0

# Max results from one source. Scales with corpus heterogeneity — in a corpus
# with 30+ source docs, capping at 3 is too tight for focused single-doc queries.
# Use _max_per_source(n_sources) to get the right cap dynamically.
_MAX_PER_SOURCE_BASE = 3
_MAX_PER_SOURCE_LARGE = 6   # for corpora with many diverse source documents

def _max_per_source(n_sources: int) -> int:
    """Return per-source cap depending on how many distinct sources are in play."""
    return _MAX_PER_SOURCE_LARGE if n_sources >= 15 else _MAX_PER_SOURCE_BASE

# Small-doc boost threshold: documents with fewer total chunks get a score boost
# to counteract the TF-IDF frequency disadvantage of short documents.
_SMALL_DOC_THRESHOLD = 500   # raised to 500 so short-but-dense docs also benefit
_SMALL_DOC_MAX_BOOST = 1.5


# ---------------------------------------------------------------------------
class QueryUnderstandingAgent:
    def plan(self, question: str, engine: Engine) -> QueryPlan:
        q = question.lower()
        cfg = engine.settings["retrieval"]
        plan = QueryPlan(question=question, top_k=cfg["default_top_k"],
                         use_bm25=cfg.get("hybrid", True))

        if any(w in q for w in REL_WORDS):
            plan.intent = "relationship"; plan.use_graph = True
        if any(w in q for w in TIMELINE_WORDS):
            plan.intent = "timeline"; plan.use_graph = True; plan.use_metadata = True
        if any(w in q for w in TABLE_WORDS):
            plan.intent = "table"
        if any(w in q for w in VISUAL_WORDS):
            plan.intent = "visual"
        if any(w in q for w in ENTITY_WORDS):
            plan.intent = "entity"; plan.use_graph = True
        if any(w in q for w in ALL_WORDS):
            plan.intent = "multi"
        if "pattern" in q or "across" in q:
            plan.use_graph = True
        # Domain-specific intent hints stored in plan.filters for routing
        if any(w in q for w in MANUFACTURE_WORDS):
            plan.intent = "table"; plan.filters["domain"] = "manufacture"
        if any(w in q for w in EXPORT_WORDS):
            plan.filters["domain"] = "export"
        if any(w in q for w in IMPORT_WORDS):
            plan.filters["domain"] = "import"
        if any(w in q for w in GHOST_GUN_WORDS):
            plan.filters["domain"] = "pmf"
        if any(w in q for w in TRACE_WORDS):
            plan.filters["domain"] = "trace"
        if any(w in q for w in THEFT_WORDS):
            plan.filters["domain"] = "theft"
        if any(w in q for w in ARSON_WORDS):
            plan.filters["domain"] = "arson"
        if any(w in q for w in EXPLOSIVE_WORDS):
            plan.filters["domain"] = "explosives"
        if any(w in q for w in SELLING_WORDS):
            plan.filters["domain"] = "selling"

        # date / location filters -> metadata retrieval
        if re.search(r"\b(19|20)\d{2}\b", q) or " in 20" in q:
            plan.use_metadata = True
        plan.reason = (f"intent={plan.intent}; graph={plan.use_graph}; "
                       f"meta={plan.use_metadata}; hybrid={plan.use_bm25}; "
                       f"domain={plan.filters.get('domain', '')}")

        # Optional LLM refinement (only if a real LLM is configured AND enabled).
        # Gated by config so the eval harness can pin deterministic retrieval
        # (LLM refinement varies top_k run-to-run even at temperature 0).
        if engine.llm.name != "offline" and cfg.get("llm_refine", True):
            self._llm_refine(question, plan, engine)
        return plan

    def _llm_refine(self, question: str, plan: QueryPlan, engine: Engine) -> None:
        sys = ("Classify the user question for a GraphRAG retriever. Respond with "
               "ONLY JSON: {\"intent\": one of "
               "[fact,entity,relationship,pattern,timeline,table,visual,multi], "
               "\"use_graph\": bool, \"use_metadata\": bool, \"top_k\": int}.")
        try:
            out = engine.llm.complete(question, system=sys, temperature=0.0,
                                      max_tokens=120)
            m = re.search(r"\{.*\}", out, re.S)
            if m:
                d = json.loads(m.group(0))
                plan.intent = d.get("intent", plan.intent)
                plan.use_graph = bool(d.get("use_graph", plan.use_graph))
                plan.use_metadata = bool(d.get("use_metadata", plan.use_metadata))
                plan.top_k = int(d.get("top_k", plan.top_k))
                plan.reason += " | llm-refined"
        except Exception:  # noqa: BLE001
            pass


class CorpusSelectionAgent:
    def select(self, plan: QueryPlan, engine: Engine) -> List[str]:
        q = plan.question.lower()
        available = [c for c in engine.corpora if engine.vstore(c).count() > 0]

        # 1) Explicit programmatic isolation: the API/UI can pin one or more
        #    corpuses via plan.filters["corpus"]. Honoured verbatim (intersected
        #    with what's available) — this is how a caller queries in isolation.
        explicit = plan.filters.get("corpus")
        if explicit:
            req = [explicit] if isinstance(explicit, str) else list(explicit)
            scoped = [c for c in req if c in available]
            return scoped or req

        if plan.intent == "multi" or not available:
            return available or list(engine.corpora)

        chosen = []
        # 2) Explicit corpus name mentioned in the question ("the web corpus",
        #    "pdf documents", "visual data") scopes retrieval to that corpus.
        for name in engine.corpora:
            if f"{name} corpus" in q or f"{name} documents" in q:
                chosen.append(name)
        # 3) Heuristic routing by topic words.
        if any(w in q for w in ("website", "web ", "site", "online", "url")):
            chosen.append("web")
        if any(w in q for w in VISUAL_WORDS) or plan.intent == "visual":
            chosen.append("visual")
        if "collection" in q or "across documents" in q:
            chosen.append("connected")
        # De-dup, keep order, intersect with available.
        seen = set()
        chosen = [c for c in chosen if c in available
                  and not (c in seen or seen.add(c))]
        return chosen or available


def _get_bm25(corpus_name: str, vs) -> Tuple["BM25", Dict[str, int]]:
    """Return a cached (BM25, source_chunk_counts) for this corpus.

    source_chunk_counts maps each source_name to its total chunk count in the
    corpus — used to apply a small-doc boost in retrieval so short documents
    don't lose to large ones purely due to TF-IDF frequency effects.
    """
    count = vs.count()
    cached = _BM25_CACHE.get(corpus_name)
    if cached and cached[0] == count:
        return cached[1], cached[2]
    chunks = vs.all_chunks()
    bm = BM25(chunks)
    source_counts: Dict[str, int] = {}
    for c in chunks:
        src = c.source_name or c.document_title or ""
        source_counts[src] = source_counts.get(src, 0) + 1
    _BM25_CACHE[corpus_name] = (count, bm, source_counts)
    return bm, source_counts


def _apply_source_diversity(hits: List[RetrievalHit],
                             max_per_source: int = _MAX_PER_SOURCE_BASE) -> List[RetrievalHit]:
    """Cap the number of chunks returned from any single source document so that
    large documents do not flood the result set and crowd out smaller ones.
    Iterates through hits in score-descending order and keeps at most
    max_per_source from each source."""
    counts: Dict[str, int] = defaultdict(int)
    result: List[RetrievalHit] = []
    for h in hits:
        key = h.chunk.source_name or h.chunk.document_title or h.chunk.corpus
        if counts[key] < max_per_source:
            counts[key] += 1
            result.append(h)
    return result


class RetrievalAgent:
    def retrieve(self, plan: QueryPlan, corpora: List[str],
                 engine: Engine) -> List[RetrievalHit]:
        qvec = engine.embedder.embed_one(plan.question)
        merged: Dict[str, RetrievalHit] = {}

        def add(chunk: ChunkRecord, score: float, source: str):
            ex = merged.get(chunk.chunk_id)
            if ex is None or score > ex.score:
                merged[chunk.chunk_id] = RetrievalHit(chunk=chunk, score=score,
                                                      source=source)

        # Small boost for table/chart/figure chunks when the query intent is table/visual.
        # Kept small (1.05) to avoid over-boosting NOTE/caption chunks that the chunker
        # mis-classifies as tables; higher values caused state-list text chunks to lose
        # to low-content table-typed NOTE chunks for source-state queries.
        content_boost = 1.05 if plan.intent in ("table", "visual") else 1.0

        where = self._filter(plan)
        all_source_counts: Dict[str, int] = {}

        # Domain pre-fetch: when a targeted domain is set, the best chunks for
        # that domain may not survive the generic top-K cut because they lack
        # common query terms (e.g., AFMER tables don't say "United States").
        # Pre-fetch from domain-matched sources so boosts have chunks to act on.
        _DOMAIN_PREFETCH_KEYWORDS = {
            "manufacture": ("afmer",),
            "export":      ("nfcta_export",),
            "selling":     ("nfcta_selling",),
        }
        domain = plan.filters.get("domain", "")
        prefetch_kws = _DOMAIN_PREFETCH_KEYWORDS.get(domain, ())

        for corpus in corpora:
            vs = engine.vstore(corpus)
            for chunk, s in vs.search(qvec, plan.top_k * 3, where=where):
                boost = content_boost if chunk.content_type in ("table", "chart", "figure") else 1.0
                add(chunk, s * boost, "vector")
            if plan.use_bm25:
                bm, sc = _get_bm25(corpus, vs)
                all_source_counts.update(sc)
                for chunk, s in bm.search(plan.question, plan.top_k * 2):
                    boost = content_boost if chunk.content_type in ("table", "chart", "figure") else 1.0
                    add(chunk, 0.75 * s * boost, "bm25")

            # Domain pre-fetch: inject top chunks from domain-targeted sources
            if prefetch_kws:
                def _src_filter(payload: Dict, kws=prefetch_kws) -> bool:
                    src = (payload.get("source_name") or "").lower()
                    return any(kw in src for kw in kws)
                for chunk, s in vs.search(qvec, plan.top_k * 2, where=_src_filter):
                    boost = content_boost if chunk.content_type in ("table", "chart", "figure") else 1.0
                    add(chunk, s * boost, "vector")

        graph_paths: List[str] = []
        if plan.use_graph:
            # Personalized-PageRank retrieval for relationship/pattern queries
            # when enabled (HippoRAG-style); otherwise BFS subgraph expansion.
            gr_mode = engine.settings["retrieval"].get("graph_retriever", "bfs")
            if gr_mode == "ppr" and plan.intent in ("relationship", "pattern"):
                graph_paths = self._graph_expand_ppr(plan, corpora, engine, add)
            else:
                graph_paths = self._graph_expand(plan, corpora, engine, add)

        hits = list(merged.values())

        # Chunk quality filter: penalise navigation/TOC/URL/summary garbage so
        # that high-BM25-scoring but low-content chunks don't crowd out real data.
        for h in hits:
            q = _chunk_quality(h.chunk)
            if q < 1.0:
                h.score *= q

        # Year-boost: when query mentions a year:
        #   +30% for year-matched docs (doc_date or source name contains query year)
        #   -20% for year-MISMATCHED dated docs (doc has a year but it's the wrong year)
        #   -15% for undated docs (no year signal at all)
        # The mismatch penalty is needed to prevent, e.g., a small explosives_2022 doc
        # (with 1.5× small-doc boost) from crowding out explosives_2024 when the query
        # asks about 2024.
        _qyears = re.findall(r'\b((?:19|20)\d{2})\b', plan.question)
        if _qyears:
            for h in hits:
                src = h.chunk.source_name or h.chunk.document_title or ""
                doc_date = h.chunk.document_date or ""
                if any(yr in src or yr in doc_date for yr in _qyears):
                    h.score = h.score * 1.30    # year-matched: +30%
                elif doc_date:
                    h.score = h.score * 0.80    # dated but wrong year: -20%
                else:
                    h.score = h.score * 0.85    # undated: -15%

        # Small-doc boost: documents with few total chunks get a boost to
        # compensate for their lower TF-IDF/BM25 frequency scores vs large docs.
        if all_source_counts:
            for h in hits:
                src = h.chunk.source_name or h.chunk.document_title or ""
                n = all_source_counts.get(src, 9999)
                if n < _SMALL_DOC_THRESHOLD:
                    boost_factor = min(_SMALL_DOC_MAX_BOOST, _SMALL_DOC_THRESHOLD / max(n, 50))
                    h.score = h.score * boost_factor

        # Domain-intent boost: only for domains where semantic similarity alone
        # fails to surface the right document (e.g., "export" is confused with
        # "import" semantically; "selling" data lives in a non-obvious file).
        # Domains like trace/theft/arson/explosives already work via semantics —
        # boosting them uniformly buries the specific table chunk behind intro text.
        domain = plan.filters.get("domain", "")
        # Stronger boosts for domains where semantics routinely mis-route:
        # - "export" queries retrieve nfcta_imports (both describe country×firearm tables)
        # - "selling" queries retrieve trace data (both list calibers by count)
        # - "manufacture" queries retrieve commerce_2024 instead of AFMER
        # Use a 1.8x boost so even a 1.5× small-doc advantage on the wrong doc is overcome.
        _DOMAIN_BOOST_KEYWORDS = {
            "export":      ("nfcta_export",),
            "pmf":         ("pmf", "privately_made", "ghost"),
            "manufacture": ("afmer",),          # only AFMER has annual mfg totals
            "selling":     ("nfcta_selling",),  # caliber/sales data
        }
        if domain and domain in _DOMAIN_BOOST_KEYWORDS:
            kws = _DOMAIN_BOOST_KEYWORDS[domain]
            for h in hits:
                src = (h.chunk.source_name or "").lower()
                if any(kw in src for kw in kws):
                    h.score = h.score * 1.80    # strong domain-source boost

        # Stable tie-break by chunk_id: equal-score hits (e.g. graph-expansion
        # hits all at 0.5) are otherwise ordered by set-iteration, which varies
        # across processes under PYTHONHASHSEED and makes NDCG/MRR non-reproducible.
        hits.sort(key=lambda h: (-h.score, h.chunk.chunk_id))
        # Keep a wider pool before diversity capping so boosts can reorder things.
        hits = hits[:max(plan.top_k * 5, 60)]

        # Determine how many distinct source documents are in the candidate pool.
        # For diverse corpora (30+ docs) we allow more chunks per source so that
        # focused single-doc queries can still surface the right answer.
        n_distinct = len({h.chunk.source_name or h.chunk.document_title for h in hits})
        per_src = _max_per_source(n_distinct)

        # Apply source diversity to prevent any single large document dominating
        hits = _apply_source_diversity(hits, max_per_source=per_src)

        self.last_graph_paths = graph_paths
        return hits

    def _filter(self, plan: QueryPlan):
        # "domain" is a scoring hint, not a hard filter — exclude it from where().
        f = {k: v for k, v in (plan.filters or {}).items() if k != "domain"}
        years: List[str] = []
        if plan.use_metadata:
            years = re.findall(r"\b((?:19|20)\d{2})\b", plan.question)
        if not f and not years:
            return None

        def where(payload: Dict) -> bool:
            if years:
                doc_date = payload.get("document_date", "") + payload.get("incident_date", "")
                # Accept chunk if it matches ANY year in the query, OR has no date set
                # (undated docs like nfcta_exports.pdf are always included).
                if doc_date and not any(yr in doc_date for yr in years):
                    return False
            for k, v in f.items():
                if str(v).lower() not in str(payload.get(k, "")).lower():
                    return False
            return True
        return where

    def _graph_expand_ppr(self, plan, corpora, engine, add) -> List[str]:
        """Personalized-PageRank graph retrieval over the typed graph.

        Seeds on the query's entity nodes, ranks chunks by centrality, and adds
        them scaled into the 0.5-0.7 band (above co-occurrence, below direct
        vector hits). Falls back to BFS expansion if networkx is unavailable."""
        from .graph_retriever import GraphRetriever
        g = engine.graph
        if not hasattr(self, "_ppr") or self._ppr.g is not g:
            self._ppr = GraphRetriever(g)
        if not self._ppr.available():
            return self._graph_expand(plan, corpora, engine, add)

        terms = content_tokens(plan.question)
        seeds, matched = [], []
        for t in terms:
            node = g.find(t)
            if node and node not in seeds:
                seeds.append(node)
                matched.append(node)
        ranked = self._ppr.rank_chunks(seeds, top_k=max(plan.top_k * 3, 30))
        if not ranked:
            return self._graph_expand(plan, corpora, engine, add)

        # Normalise PageRank scores into a 0.50-0.70 contribution band.
        top = ranked[0][1] or 1.0
        cid_score = {cid: 0.50 + 0.20 * (s / top) for cid, s in ranked}
        for corpus in corpora:
            vs = engine.vstore(corpus)
            for cid, sc in cid_score.items():
                ch = vs.get(cid)
                if ch:
                    add(ch, sc, "graph")

        # Typed relationship paths for the answer's evidence.
        paths: List[str] = []
        for i in range(len(matched)):
            for j in range(i + 1, min(i + 3, len(matched))):
                labelled = g.path_labeled(matched[i], matched[j])
                if labelled:
                    paths.append(labelled)
        return paths[:8]

    def _graph_expand(self, plan, corpora, engine, add) -> List[str]:
        g = engine.graph
        hops = engine.settings["retrieval"]["graph_hops"]
        terms = content_tokens(plan.question)
        matched = []
        for t in terms:
            node = g.find(t)
            if node and node not in matched:
                matched.append(node)

        # Collect chunks reachable via TYPED edges separately from co-occurrence:
        # typed paths are higher signal, so their chunks enter at a higher score.
        typed_chunks: set = set()
        all_chunks: set = set()
        for node in matched[:6]:
            typed_chunks |= g.subgraph_chunks_typed(node, hops)
            all_chunks |= g.subgraph_chunks(node, hops)
        co_only = all_chunks - typed_chunks

        # Prefer typed relationship paths (labelled with their relation) and
        # fall back to a plain co-occurrence path when no typed path exists.
        paths: List[str] = []
        for i in range(len(matched)):
            for j in range(i + 1, min(i + 3, len(matched))):
                labelled = g.path_labeled(matched[i], matched[j])
                if labelled:
                    paths.append(labelled)
                else:
                    p = g.path(matched[i], matched[j])
                    if p:
                        paths.append(" -> ".join(p))

        for corpus in corpora:
            vs = engine.vstore(corpus)
            for cid in typed_chunks:
                ch = vs.get(cid)
                if ch:
                    add(ch, 0.65, "graph")   # typed-path evidence scores above 0.5
            for cid in co_only:
                ch = vs.get(cid)
                if ch:
                    add(ch, 0.5, "graph")
        return paths[:8]


class EvaluationAgent:
    """Scores relevance/confidence/completeness; drops weak evidence."""
    def evaluate(self, plan: QueryPlan, hits: List[RetrievalHit],
                 engine: Engine) -> List[RetrievalHit]:
        qtok = set(content_tokens(plan.question))
        qvec = engine.embedder.embed_one(plan.question)
        kept: List[RetrievalHit] = []
        for h in hits:
            ctok = set(content_tokens(h.chunk.text))
            overlap = len(qtok & ctok) / (len(qtok) or 1)
            sim = cosine(qvec, engine.embedder.embed_one(h.chunk.text))
            completeness = min(1.0, len(h.chunk.text) / 400.0)
            meta_bonus = 0.1 if (h.chunk.entities or h.chunk.case_reference) else 0.0
            # Content-type bonus: table/chart chunks get a boost for table/visual intents
            ctype_bonus = 0.0
            if plan.intent in ("table", "visual") and h.chunk.content_type in ("table", "chart", "figure"):
                ctype_bonus = 0.12
            src_q = {"vector": 1.0, "graph": 0.95, "bm25": 0.85}.get(h.source, 0.8)
            score = (0.45 * sim + 0.30 * overlap + 0.15 * completeness +
                     meta_bonus + ctype_bonus) * src_q * float(h.chunk.confidence or 1.0)
            h.eval_score = round(score, 4)
            h.eval_notes = (f"sim={sim:.2f} overlap={overlap:.2f} "
                            f"src={h.source} ctype={h.chunk.content_type}")
            kept.append(h)
        thr = engine.settings["retrieval"]["min_confidence"]
        strong = [h for h in kept if (h.eval_score or 0) >= thr]
        strong.sort(key=lambda h: (-(h.eval_score or 0), h.chunk.chunk_id))
        return strong or sorted(
            kept, key=lambda h: (-(h.eval_score or 0), h.chunk.chunk_id))[:plan.top_k]


class RerankingAgent:
    def rerank(self, plan: QueryPlan, hits: List[RetrievalHit],
               engine: Engine) -> List[RetrievalHit]:
        rcfg = engine.settings["reranker"]
        qtok = set(content_tokens(plan.question))
        for h in hits:
            ctok = set(content_tokens(h.chunk.text))
            coverage = len(qtok & ctok) / (len(qtok) or 1)
            ctype_bonus = 0.08 if (
                plan.intent in ("table", "visual") and
                h.chunk.content_type in ("table", "chart", "figure")
            ) else 0.0
            h.rerank_score = round(0.7 * (h.eval_score or 0) + 0.3 * coverage + ctype_bonus, 4)
        if rcfg["provider"] == "llm" and engine.llm.name != "offline":
            self._llm_rerank(plan, hits, engine)

        # Provider reranker (e.g. cross-encoder BGEReranker). Returns a reordered
        # list to override the linear blend, or None to keep it (local/llm).
        reranker = getattr(engine, "reranker", None)
        if reranker is not None:
            reordered = reranker.rerank(plan.question, hits)
            if reordered is not None:
                return reordered[:plan.top_k]

        hits.sort(key=lambda h: (-(h.rerank_score or 0), h.chunk.chunk_id))
        return hits[:plan.top_k]

    def _llm_rerank(self, plan, hits, engine) -> None:
        try:
            listing = "\n".join(f"[{i}] {h.chunk.text[:200]}"
                                for i, h in enumerate(hits[:10]))
            sys = ("Rank passages by relevance to the question. Respond ONLY with "
                   "a JSON list of indices best-first, e.g. [3,0,1].")
            out = engine.llm.complete(f"Q: {plan.question}\n{listing}",
                                      system=sys, temperature=0.0, max_tokens=80)
            order = json.loads(re.search(r"\[.*\]", out, re.S).group(0))
            for rank, idx in enumerate(order):
                if 0 <= idx < len(hits):
                    hits[idx].rerank_score = (hits[idx].rerank_score or 0) + \
                        (len(order) - rank) * 0.05
        except Exception:  # noqa: BLE001
            pass


class GenerationAgent:
    def generate(self, plan: QueryPlan, hits: List[RetrievalHit],
                 graph_paths: List[str], engine: Engine) -> Answer:
        citations = []
        ctx_lines = []
        for i, h in enumerate(hits, 1):
            c = h.chunk
            tag = f"[{i}]"
            loc = f"p.{c.page_number}" if c.page_number else c.corpus
            # Prefix label for structured content so the LLM knows what type it is
            ctype_label = ""
            if c.content_type in ("table", "chart", "figure"):
                ctype_label = f" [{c.content_type.upper()}]"
            cite = {"ref": i, "source": c.source_name or c.document_title,
                    "page": c.page_number, "corpus": c.corpus,
                    "url": c.source_url, "chunk_id": c.chunk_id,
                    "confidence": h.eval_score, "method": c.extraction_method,
                    "content_type": c.content_type}
            citations.append(cite)
            ctx_lines.append(f"{tag}{ctype_label} ({c.source_name or c.document_title}, {loc}) "
                             f"{c.text}")
        context = "\n".join(ctx_lines) if ctx_lines else "(no evidence retrieved)"
        gp = ("\nKNOWN RELATIONSHIP PATHS:\n" + "\n".join(graph_paths)) \
            if graph_paths else ""

        sys = ("You are an analyst for ATF-related data. Answer ONLY from the "
               "provided context. Cite every claim with [n] referring to the "
               "context items. Items labelled [TABLE] contain structured data — "
               "extract specific numbers and values from them. Items labelled "
               "[CHART] or [FIGURE] contain visual summaries — use their "
               "descriptions. If the context is insufficient, say so. When "
               "relationships or patterns are present, explain them.")
        prompt = (f"QUESTION: {plan.question}\n\nCONTEXT:\n{context}{gp}\n\n"
                  "Provide a clear, source-cited answer.")
        answer_text = engine.llm.complete(prompt, system=sys)

        confs = [h.eval_score or 0 for h in hits[:5]]
        confidence = round(sum(confs) / len(confs), 3) if confs else 0.0
        return Answer(question=plan.question, answer=answer_text,
                      citations=citations, confidence=confidence,
                      plan=plan.__dict__, graph_paths=graph_paths,
                      evidence_count=len(hits))
